### ISSUE TITLE
PHP/Source Engine - Player list with 'status' does not work if status returns too much data

### ISSUE THREAD

**Issue by ArgHereBeDragons** [koraktor/steam-condenser#17] opened 2009-08-12 06:26 UTC
I can confirm that if there are only a few players on the server, the player list with rcon password supplied populates the objects properly but if there is too much data, the socket objects do not return the correct data and the extended information on the players does not get set.

**Comment by ArgHereBeDragons** [comment] 2009-08-23 02:09
Any timeline on a fix for this? Ive integrated steam-condenser into my webapp already and id rather get a fix then rework a different framework. 

It seems like its a split packet issue.

**Comment by koraktor** [comment] 2009-08-29 17:11
Sorry for not replying for such a long time.
Do you have any further information on this bug? I tested that feature with a local server full of bots, so it worked for many players (and split packets).

I would really appreciate any detail you can provide.

**Comment by koraktor** [comment] 2009-09-01 08:51
A related problem has been fixed in 58b508a462027a84634489ff2e980a3a7af0b68b.

The root cause for this problem seems to be a reduced MTU (or similar ISP setting) resulting in smaller packets than the usual 1440 bytes. A fix is in the works, thanks to Arg.

**Comment by koraktor** [comment] 2009-09-11 09:18
The MTU problem is now fixed in bb7ea8de75573a75d87e32226d1ccd6e9f060131.

**Closed as completed by koraktor** 2009-09-11 09:18 UTC
Labels: Bug
