### ISSUE TITLE
some errors with ruby.

### ISSUE THREAD

**Issue by m4tm4t** [koraktor/steam-condenser#128] opened 2011-10-10 00:53 UTC
Hi,
I'm trying to use it from rails, but there is some problems with SourceServer (not tested others)

I'm getting `SteamCondenser::TimeoutError` when trying to set hostname via `rcon_exec("hostname myhostname")`
I'm getting `RCONBanError` when trying exec config file via `rcon_exec("exec server.cfg")` (i'm not banned...)
 What happens?

**Comment by koraktor** [comment] 2011-10-10 05:54
This may be because of `hostname` and `exec` commands not returning an answer to the client, although I have to verify this.

Can you post the complete backtrace for both actions?

**Comment by m4tm4t** [comment] 2011-10-10 10:31
Of course :)

`rcon_exec("hostname myhostname")`

```
SteamCondenser::TimeoutError in Server#show 
The operation timed out.

extras/rcon/steam/sockets/steam_socket.rb:55:in `receive_packet'
extras/rcon/steam/sockets/rcon_socket.rb:80:in `reply'
extras/rcon/steam/servers/source_server.rb:89:in `rcon_exec'
```

`rcon_exec("exec server.cfg")`

```
RCONBanError in Server#show 
You have been banned from this server.

extras/rcon/steam/sockets/rcon_socket.rb:80:in `reply'
extras/rcon/steam/servers/source_server.rb:89:in `rcon_exec'
```

**Comment by koraktor** [comment] 2011-10-19 19:15
First of all sorry for the late reply.

I was able to fix the `TimeoutError` for e.g. the `hostname` command. It was indeed caused by an empty reply from the server.
The `RCONBanError` seems to have a different cause (although a succesful `exec server.cfg` will also return nothing). I tested a minimal config which worked just fine. I'd guess that the contents of your `server.cfg` are causing this trouble. Maybe setting some RCON related stuff in the config will cause the server to reset RCON connection or something similar.

**Comment by m4tm4t** [comment] 2011-10-21 01:02
Ok I will try soon
I am surprised that the RCONBanError may come from config file, rcon doesn't parse it.
Once I have more time I will look at the code closer.

**Comment by koraktor** [comment] 2011-10-21 06:14
> I am surprised that the RCONBanError may come from config file, rcon doesn't parse it.

The RCON protocol itself does not, right. But the server does and perhaps (this is really a blind guess) it's causing RCON connections to be resetted. Maybe you can send me a copy of your `server.cfg` with any sensible data removed. That way I might cross-check this on my test server.

**Comment by m4tm4t** [comment] 2011-10-21 06:40
`server.cfg` http://tools.foohey.me/paste/5
created with a simple ruby "template": http://tools.foohey.me/paste/6

**Comment by koraktor** [comment] 2011-10-21 06:48
Alright, maybe setting the `rcon_password` is causing the reset. You could try to remove that line from `server.cfg` and try again.

**Comment by m4tm4t** [comment] 2011-10-21 07:22
ah, it's a possibility, but if I remember, I used https://github.com/rads/rcon without problems (with exec .cfg files)
I found solution: send game commands directly through screen session (the good: faster, the bad: no response message)

**Comment by koraktor** [comment] 2011-10-21 07:30
[rads/rcon](https://github.com/rads/rcon) seems to have no logic to detect bans.

I don't state that my method is entirely bullet proof, but it works as expected. This edge case seems to be caused by an undocumented behaviour of the protocol. I will try to find a workaround, but I don't think this is a bug in my implementation.

**Comment by m4tm4t** [comment] 2011-10-22 01:45
I confirm that the cvar `rcon_password` in cfg break the `exec server.cfg` reply, but the command is executed successfully

8daa36b8371e3cfc951e987ed12f3db9786ce605 while waiting a real fix

**Comment by koraktor** [comment] 2011-10-23 18:10
Ok, so the cause is now identified. It's pretty clear now. SourceDS has to do this, because Source's RCON connections are persistent (TCP). If the password changes, the server has to kill the connections to be sure no one uses the old password.

> ... while waiting a real fix

There won't be a real fix. Sorry. As this is a feature of SourceDS I won't add any workarounds to capture some single edge case. In fact, your patch leaves the `RCONSocket` in an inconsistent state. The `RCONBanError` will still be raised when you call another command using the same socket, because the "ban" will already be sent by the server. Additionally not every call to `exec` will cause that error and it might be useful to see the reply from the server as it may hint at non-existant config files etc.

I would suggest a different approach:

Rescue from the `RCONBanError` in you're own code. If you have a pre-defined action that re-reads the server config I would do something like this:

``` ruby
def reread_config
  begin
    # Let's say @server already exists and #rcon_auth was already called
    @server.rcon_exec 'status' # Do something unintrusive here, just to check for a real ban

    begin
      @server.rcon_exec 'exec server.cfg'
    rescue RCONBanError
       # This RCONBanError was expected, we can safely ignore it
    end
  rescue RCONNoAuthError
    # Something went wrong here, maybe #rcon_auth wasn't successful
  rescue RCONBanError
    # This client has been banned for real
  end

  respond_to do |format|
    format.html
  end
end
```

I'm going to close this issue because the other problem has been fixed. But feel free to further discuss on the `exec` problem.

**Closed as completed by koraktor** 2011-10-23 18:10 UTC
Labels: RCON, Bug, Source servers

**Comment by m4tm4t** [comment] 2011-10-23 23:55
you're right, I was not think that way, thank you
