### ISSUE TITLE
XML data could not be parsed: null [Java]

### ISSUE THREAD

**Issue by afij** [koraktor/steam-condenser#245] opened 2014-04-30 08:10 UTC
I have been messing around with the API but I am halted before I can really try things out when I make a new SteamId object:

``` java
id = SteamId.create("FiJi");
```

I receive the following error when the application steps through the XMLData(String url) method somewhere in the document builder.

I have this profile's XML can be reached online (http://steamcommunity.com/id/fiji?xml=1) but cannot be translated properly. From what I have read the XML output is deprecated but things should still work. Any ideas? If you require more info just let me know.

**Comment by koraktor** [comment] 2014-04-30 08:39
The given profile works flawlessly for me.
This may probably caused by Steam sending errors (e.g. "internal server error") as HTML output instead of XML.

Maybe you can provide a full stacktrace of the exception.

**Comment by afij** [comment] 2014-04-30 20:47
I have worked past this error (needed a jar) and have continued to venture into a seperate issue when working with GameInventory. 

The app queries the Steam Web API to get grab /GetPlayerItems/ but warns;

04-30 16:36:49.244: I/dalvikvm(11184): Could not find method org.json.JSONObject.getNames, referenced from method com.github.koraktor.steamcondenser.steam.community.GameItem.<init>
04-30 16:36:49.244: W/dalvikvm(11184): VFY: unable to resolve static method 13018: Lorg/json/JSONObject;.getNames (Lorg/json/JSONObject;)[Ljava/lang/String;

Further down into the stack there is a runtime exception:

04-30 16:36:54.834: E/AndroidRuntime(11184): FATAL EXCEPTION: AsyncTask #1
04-30 16:36:54.834: E/AndroidRuntime(11184): java.lang.RuntimeException: An error occured while executing doInBackground()
04-30 16:36:54.834: E/AndroidRuntime(11184):    at android.os.AsyncTask$3.done(AsyncTask.java:278)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at java.lang.Thread.run(Thread.java:856)
04-30 16:36:54.834: E/AndroidRuntime(11184): Caused by: java.lang.ClassCastException: java.lang.NoSuchMethodError cannot be cast to java.lang.RuntimeException
04-30 16:36:54.834: E/AndroidRuntime(11184):    at com.github.koraktor.steamcondenser.steam.community.GameInventory.fetch(GameInventory.java:224)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at com.github.koraktor.steamcondenser.steam.community.GameInventory.<init>(GameInventory.java:188)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at com.github.koraktor.steamcondenser.steam.community.tf2.TF2Inventory.<init>(TF2Inventory.java:118)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at com.github.koraktor.steamcondenser.steam.community.GameInventory.create(GameInventory.java:136)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at com.github.koraktor.steamcondenser.steam.community.GameInventory.create(GameInventory.java:103)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at com.github.koraktor.steamcondenser.steam.community.GameInventory.create(GameInventory.java:86)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at com.example.testapi.Items$GetInventory.doInBackground(Items.java:124)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at com.example.testapi.Items$GetInventory.doInBackground(Items.java:1)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at android.os.AsyncTask$2.call(AsyncTask.java:264)
04-30 16:36:54.834: E/AndroidRuntime(11184):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
04-30 16:36:54.834: E/AndroidRuntime(11184):    ... 5 more

Not sure if the two things are related but this is my current challenge! Any help would be welcome.

**Comment by koraktor** [comment] 2014-05-01 06:21
That sounds like the the JSON library is also missing.

I don't know if this is possible for Android, but you should use Maven or a compatible build environment to get all dependencies right. Otherwise have a look at the `pom.xml`.

**Comment by afij** [comment] 2014-05-01 12:33
I have added the JSON library to my build path and have noticed that no other JSONObject methods that appear before .getNames() have this problem. 

I have looked into/attempted to add maven into my android project but I haven't been able to get anything to work properly. I will keep looking around for a solution.

**Comment by koraktor** [comment] 2014-05-01 12:36
Currently Steam Condenser depends on [this slightly outdated version of JSON](http://search.maven.org/#artifactdetails%7Corg.json%7Cjson%7C20090211%7Cjar). I don't know if the newer ones are compatible, so you might try to use this one explicitly.

**Comment by afij** [comment] 2014-05-01 13:19
I believe I found the problem. The org.json included with android does NOT contain that method (http://developer.android.com/reference/org/json/JSONObject.html) while the one steam-condenser does have it.  This means for some reason my project is not referencing the correct library when compiling.

I cannot get my project to point to the correct one though. I have tried to add the jar you just gave me to the build path but it still does not get the right one when I import it into a class for testing.

**Comment by koraktor** [comment] 2014-05-01 14:54
I have little experience developing Android apps, so I don't know if there's a way to override system libraries with custom JARs. Maybe there's some way to control the classpath during runtime.

**Comment by afij** [comment] 2014-05-02 03:36
I have corrected all the errors by tediously adding steam-condenser to my own package to point them in the right direction.

Next question I have is for creating a GameInventory? Does creating an inventory for something like TF2 normally take up alot of memory. I'm able list off items from an inventory but when I test on mobile I run into memory issues. Looks like it's from how deep the querying goes inside itself.

Thanks for all the help so far!

----- Reply message -----

**Comment by koraktor** [comment] 2014-06-22 12:40
Sorry for the late response.

Especially the item schema might require a bit of memory. The raw item schema of TF2 is 3.6MB for example. The raw data is not explicitly held in memory by Steam Condenser, but must be parsed to JSON objects and additionally parsed to Steam Condenser's `GameItemSchema`. I don't have any numbers, but I'd assume that this should be possible on a modern Android device.

I'll close this, but feel free to open a new issue if memory is still a problem for you.

**Closed as completed by koraktor** 2014-06-22 12:40 UTC
Labels: Java, Community, Compatibility
