### ISSUE TITLE
1.3.3 - CS:GO - JAVA - how to detect if server is running.

### ISSUE THREAD

**Issue by danielsawan** [koraktor/steam-condenser#203] opened 2013-03-14 14:54 UTC
Hi i am searching for a way to detect if the server is online, and can accept players. Sometime when users install some mod on the server and try to start it the server just go into a zombie process. (By zombie i mean the server is not started and the process will still running). So when i detect this zombie server i just kill -9 it.
The problem is the detection of this sort of server. Until now i use this code.
i have a method named is alive() which contain : 

```
    try {
     SourceServer csSrv = new SourceServer(getInetAdress(), serverPort);
        csSrv.initialize();
        csSrv.isRconAuthenticated();
        return true;
    } catch (Exception e){
        return false;
    }
```

It work very well but if you spam this method for a strange reason it will go into exception java.util.concurrent.TimeoutException.

Then i thought it was because i don't close any socked between 2 calls then i search for a close method and only found csSrv.disconnect();. but i call this just after csSrv.isRconAuthenticated(); i got null pointer. 

Is there a good way to detect if a server is really started and accepting connection ?

soz for my english

**Comment by danielsawan** [comment] 2013-03-18 13:22
any idea about java.util.concurrent.TimeoutException ?

**Comment by koraktor** [comment] 2013-03-19 22:26
I'll have a look at the NPE in `disconnect()`.

The timeout may be caused by various factors, I'll try to reproduce this.

But why use RCON at all? Isn't a simple query sufficient?

**Comment by danielsawan** [comment] 2013-03-19 22:36
Do you have a query example ? I use Rcon cause i only know Rcon to send command to started server.

**Comment by koraktor** [comment] 2013-03-19 22:40
The call to `initialize()` is auch a simple query (BTW it's not needed for RCON).

**Comment by danielsawan** [comment] 2013-03-19 22:46
The idea in this method is to be 100% sure that a server is started. I think that sometimes the initialize() method don't throw Exceptions even when the server is starting but crashed during the start (the process just idle).
If you have another solution i will take it ;)

**Comment by danielsawan** [comment] 2013-03-27 17:44
any news ?

**Comment by koraktor** [comment] 2013-03-27 18:52
No, not yet sorry. Didn't had time to reproduce this.

Did you try using only `initialize()` or even `getPing()`? It should throw a `TimeoutException` when the server doesn't respond within a second (by default).

**Comment by koraktor** [comment] 2013-03-29 11:53
Ok, finally found some time to have a look at it.

`GameServer#isRconAuthenticated()` is a no-op, so as long as you keep recreating the server instance, it will always return `false` (that's also why `#disconnect` threw a NPE).

Like said before, `#initialize()` (or better, because faster `#getPing()`) should be sufficient for your use case. You should probably wait for multiple pings to fail (i.e. a `TimeoutException`) before you consider your server as down or crashed.

That said, I can't see a real issue here, so I'm going to close this.

**Closed as completed by koraktor** 2013-03-29 11:53 UTC
Labels: Java, invalid

**Comment by danielsawan** [comment] 2013-03-29 11:54
yes i changed my code to getPing() for the moment it seems to work. I just hope that this command will return false when quering "zombie" servers.

**Comment by koraktor** [comment] 2013-03-29 11:58
Well no, it won't. It returns `int`.
But it will throw `TimeoutException`s on unreachable servers.

**Comment by danielsawan** [comment] 2013-03-29 12:01
yes i already catch this error to return false. But what i mean is that sometimes some server with outdated installed plugin on it will just have their process idle and players can't connect to the server even if the process is running. That's why i hope that the getPing() return exception to this sort of server. If it return exception then i just kill the process with a kill -9.
