### ISSUE TITLE
[PHP] Trouble fetching server rules

### ISSUE THREAD

**Issue by ccondrup** [koraktor/steam-condenser#22] opened 2009-10-11 22:22 UTC
Yes, me again - sorry. I want to make this work, but am still having trouble. Cloned the master today and tried to run my script against our 9x cs 1.6 servers again, it worked good as it has done on earlier versions of Condenser until I enabled fetching of server rules. This script selects one single server to connect to, it chooses the server which was last updated the longest time ago. Then connect to this server, initialize(), and then calls these methods
        $ping = $condens-getPing();
        $info = $condens-getServerInfo();
        $rules = $condens-getRules();
        $players = $condens-getPlayers($rcon);

However $rules is never filled because Condenser throws exceptions on getRules(). Below are the notices I see when running:

**Every server returns:**
    Notice: Sending packet of type "A2A_PING_Packet"... in steam-condenser/lib/steam/sockets/SteamSocket.php on line 85
    Notice: Received packet of type "A2A_ACK_Packet" in steam-condenser/lib/steam/sockets/GoldSrcSocket.php on line 84
    Notice: Sending packet of type "A2S_INFO_Packet"... in steam-condenser/lib/steam/sockets/SteamSocket.php on line 85
    Notice: Received packet of type "S2A_INFO2_Packet" in steam-condenser/lib/steam/sockets/GoldSrcSocket.php on line 84
    Notice: Sending packet of type "A2S_SERVERQUERY_GETCHALLENGE_Packet"... in steam-condenser/lib/steam/sockets/SteamSocket.php on line 85
    Notice: Expected S2C_CHALLENGE_Packet, but timed out. The server is probably offline. in steam-condenser/lib/steam/servers/GameServer.php on line 182
    Notice: Sending packet of type "A2S_RULES_Packet"... in steam-condenser/lib/steam/sockets/SteamSocket.php on line 85
    Notice: Received packet of type "S2C_CHALLENGE_Packet" in steam-condenser/lib/steam/sockets/GoldSrcSocket.php on line 84
    Notice: Expected S2A_RULES_Packet, got S2C_CHALLENGE_Packet. in steam-condenser/lib/steam/servers/GameServer.php on line 175
    Notice: Sending packet of type "A2S_RULES_Packet"... in steam-condenser/lib/steam/sockets/SteamSocket.php on line 85

**Except for sometimes they also include PING + ACK like this:**
    Notice: Sending packet of type "A2A_PING_Packet"... in steam-condenser/lib/steam/sockets/SteamSocket.php on line 85
    Notice: Received packet of type "A2A_ACK_Packet" in steam-condenser/lib/steam/sockets/GoldSrcSocket.php on line 84
    Notice: Sending packet of type "A2S_INFO_Packet"... in steam-condenser/lib/steam/sockets/SteamSocket.php on line 85
    Notice: Received packet of type "S2A_INFO2_Packet" in steam-condenser/lib/steam/sockets/GoldSrcSocket.php on line 84
    Notice: Sending packet of type "A2S_SERVERQUERY_GETCHALLENGE_Packet"... in steam-condenser/lib/steam/sockets/SteamSocket.php on line 85
    Notice: Expected S2C_CHALLENGE_Packet, but timed out. The server is probably offline. in steam-condenser/lib/steam/servers/GameServer.php on line 182
    Notice: Sending packet of type "A2A_PING_Packet"... in steam-condenser/lib/steam/sockets/SteamSocket.php on line 85
    Notice: Received packet of type "A2A_ACK_Packet" in steam-condenser/lib/steam/sockets/GoldSrcSocket.php on line 84
    Notice: Sending packet of type "A2S_RULES_Packet"... in steam-condenser/lib/steam/sockets/SteamSocket.php on line 85
    Notice: Received packet of type "S2C_CHALLENGE_Packet" in steam-condenser/lib/steam/sockets/GoldSrcSocket.php on line 84
    Notice: Expected S2A_RULES_Packet, got S2C_CHALLENGE_Packet. in steam-condenser/lib/steam/servers/GameServer.php on line 175
    Notice: Sending packet of type "A2S_RULES_Packet"... in steam-condenser/lib/steam/sockets/SteamSocket.php on line 85
## Here are the results of the various runs I tried today. Some gave exceptions, some gave errors etc

**Server 1**

run1    Exception: Unknown packet with header 0x58 received
run2    Exception: Unknown packet with header 0xe6 received
run3    Exception: Unknown packet with header 0xd7 received

**Server 2**

run1    Exception: Unknown packet with header 0x80 received
run2    Exception: Unknown packet with header 0xa9 received

**Server 3**

run1    Exception: Unknown packet with header 0xf0 received
run2    Fatal error: Class 'A2A_PLAYER_Packet' not found in steam-condenser/lib/steam/packets/SteamPacketFactory.php on line 62
run3    Exception: Unknown packet with header 0x68 received
run4    Exception: Unknown packet with header 0xd8 received

**Server 4**

run1    Exception: Unknown packet with header 0x5c received
run2    Exception: Unknown packet with header 0x64 received
run3    Exception: Master query response is missing additional 0x0A byte
run4    Error: Wrong formatted A2A_ACK packet
run5    Exception: Unknown packet with header 0x6b received
run6    Actually completed script, but rules == null. Notices:
        Notice: Sending packet of type "A2S_RULES_Packet"... in steam-condenser/lib/steam/sockets/SteamSocket.php on line 85
        Notice: Received packet of type "S2C_CHALLENGE_Packet" in steam-condenser/lib/steam/sockets/GoldSrcSocket.php on line 84
        Notice: Expected S2A_RULES_Packet, got S2C_CHALLENGE_Packet. in steam-condenser/lib/steam/servers/GameServer.php on line 175
        Notice: Sending packet of type "A2S_RULES_Packet"... in steam-condenser/lib/steam/sockets/SteamSocket.php on line 85
        Notice: Received packet of type "S2A_INFO_DETAILED_Packet" in steam-condenser/lib/steam/sockets/GoldSrcSocket.php on line 84
        Notice: Expected S2A_RULES_Packet, got S2A_INFO_DETAILED_Packet. in steam-condenser/lib/steam/servers/GameServer.php on line 175

**Server 6**

run1    Exception: Unknown packet with header 0xef received
run2    Exception: Unknown packet with header 0xf2 received
run3    Exception: Unknown packet with header 0xf5 received

**Server 7**

run1    Exception: Unknown packet with header 0x1c received
run2    Exception: Unknown packet with header 0x62 received
run3    Exception: Unknown packet with header 0xb6 received

**Server 8**

run1    Exception: Unknown packet with header 0x9e received
run2    Exception: Unknown packet with header 0xf8 received
run3    Exception: Unknown packet with header 0x25 received

**Server 9**

run1    Exception: Unknown packet with header 0x48 received
run2    Exception: Unknown packet with header 0x4b received
run3    Exception: Unknown packet with header 0x4e received

**Server 10**

Exception: Unknown packet with header 0xdf received
Exception: Unknown packet with header 0xe0 received
Exception: Unknown packet with header 0xe5 received

Are these related to our servers, to Condenser or what?
PM me if you want access to one of these servers for further testing, if you need more detailed info or if I can assist in any way.

**Comment by koraktor** [comment] 2009-10-12 09:16
Ok, let's have a look at this one...

First, the notices you get are normal (you may disable them using [`error_reporting()`](http://www.php.net/manual/de/function.error-reporting.php). Although the double ping seems weird, but this shouldn't be a problem.

You real problem is, that the replies coming from your servers are not in sync with your queries. You can tell by the random headers received. All other errors or notices you get after that are caused by packets starting with a known header, but the data after that doesn't fit to the packet type expected. This should not happen and does not happen for me.

Could you provide a packet trace using Wireshark or something similar?

**Comment by lorenz82** [comment] 2009-12-12 13:02
I get the same error with steam-condenser 0.9.0 and php 5.3.0. With php 5.2.11 everything works fine. I get the following error:
    PHP Notice:  Sending packet of type "A2S_RULES_Packet"... in query/steam/sockets/SteamSocket.php on line 85
    PHP Fatal error:  Uncaught exception 'PacketFormatException' with message 'Unknown packet with header 0xc4 received.' in query/steam/packets/SteamPacketFactory.php:91
    Stack trace:
    0 query/steam/sockets/SourceSocket.php(76): SteamPacketFactory::getPacketFromData('??????+??????|B...')
    1 query/steam/servers/GameServer.php(123): SourceSocket->getReply()
    2 query/steam/servers/GameServer.php(154): GameServer->getReply()
    3 query/steam/servers/GameServer.php(246): GameServer->handleResponseForRequest(3)
    4 query/steam/servers/GameServer.php(98): GameServer->updateRulesInfo()
    5 query/index.php(72): GameServer->getRules()
    6 {main}
    thrown in query/steam/packets/SteamPacketFactory.php on line 91

**Comment by koraktor** [comment] 2009-12-13 14:32
Ok... so this may be a problem with PHP 5.3.x. I'll take a look at this.

**Comment by ccondrup** [comment] 2009-12-13 15:17
Still waiting for my server admin to provide a Wireshark install for me to use, I will be back with that once I get it, just wanted to note that the errors in the first post were generated with PHP Version 5.2.10-pl0-gentoo

**Comment by koraktor** [comment] 2009-12-13 15:44
It seems like I could find the root cause for this one. 425ad28236803187fa013c1338e32948f2aea50b has a fix.

For some odd reason I used the "V" format in `unpack()` to get signed long integers. I have no idea why this worked in the first place, but now I'm using "l" (which is working for me on  5.3.0 and 5.2.11).

This may be related to [PHP Bug 47564](http://bugs.php.net/bug.php?id=47564) on 64 bit systems.

Please verify if this works for you.

**Comment by ccondrup** [comment] 2009-12-13 16:06
Thanks, getRules() now works on 7/8 servers for us on php 5.2.10. The server that fails keeps failing every time, same message every time:
    Fatal error: Call to undefined method S2A_PLAYER_Packet::getResponse() in /lib/steam/sockets/GoldSrcSocket.php on line 136

**Comment by koraktor** [comment] 2009-12-13 16:45
Ok. So I'll close this as fixed.

Please open up another issue for the other error you're running into. This looks really odd, as the line it hints to is related to RCON communication and should not return a `S2A_PLAYER` packet.

**Closed as completed by koraktor** 2009-12-13 16:45 UTC
Labels: PHP, Bug

**Comment by lorenz82** [comment] 2009-12-14 14:50
Thank you very much, fix works fine

**Comment by nicekiwi** [comment] 2013-10-08 07:04
I am getting this error with PHP 5.5.3.

**Comment by koraktor** [comment] 2013-10-08 07:54
@nicekiwi This issue is almost 4 years old and already fixed. Please open up a new one and provide as many detail as possible regarding the used Steam Condenser and PHP versions and the actual code.
