### ISSUE TITLE
Uncaught exception 'Exception' with message 'Could not connect socket: Success'

### ISSUE THREAD

**Issue by Dekkenn** [koraktor/steam-condenser#64] opened 2010-10-05 12:49 UTC
I keep getting this error whenever I am trying to connect to a game server.
PHP Fatal error:  Uncaught exception 'Exception' with message 'Could not connect socket: Success' in /home/dekken2/bot/SteamCondenser/lib/UDPSocket.php:45
Stack trace:
#0 /home/dekken2/bot/SteamCondenser/lib/DatagramChannel.php(47): UDPSocket->connect(Object(InetAddress), '40904')
#1 /home/dekken2/bot/SteamCondenser/lib/steam/sockets/SteamSocket.php(39): DatagramChannel->connect(Object(InetAddress), '40904')
#2 /home/dekken2/bot/SteamCondenser/lib/steam/sockets/RCONSocket.php(28): SteamSocket->__construct(Object(InetAddress), '40904')
#3 /home/dekken2/bot/SteamCondenser/lib/steam/servers/SourceServer.php(56): RCONSocket->__construct(Object(InetAddress), '40904')
#4 /home/dekken2/bot/servers.php(32): SourceServer->__construct(Object(InetAddress), '40904')
#5 /home/dekken2/bot/functions.php(725): server->is_empty()
#6 /home/dekken2/bot/MainBot.php(65): start_pickup_s3()
#7 /home/dekken2/bot/SmartIRC.php(2356): PickupBot->waitbot(Object(Net_SmartIRC), Object(Net_SmartIRC_data))
#8 /home/dekken2/bot/SmartIRC.php(2007): Net_SmartIR in /home/dekken2/bot/SteamCondenser/lib/UDPSocket.php on line 45

**Comment by koraktor** [comment] 2010-10-05 12:52
Do you have any more details about your setup? What do you want to do? What server are you querying?

PS: The port you use (40904) seems a bit strange, is that the correct one?

**Comment by Dekkenn** [comment] 2010-10-05 13:03
I am trying to send an rcon command to the server.
I am querying a TF2 server

Yes this is the port.

If you want you can take a look at the code:
http://pixelpickupbot.googlecode.com/svn/trunk/

Its not my code, but I am in contact with the code author and he is clueless as of why this returns an error.

Could it be some sort of a firewall issue on the vps that this code is hosted on?

**Comment by koraktor** [comment] 2010-10-05 13:22
The problem may be caused by my code.

Whould you please try changing the code of RCONSocket::__construct() (lib/steam/sockets/RCONSocket.php) like follows:

```
public function __construct(InetAddress $ipAddress, $portNumber) {
    $this->buffer = ByteBuffer::allocate(1400);
    $this->channel = SocketChannel::open();
    $this->remoteSocket = array($ipAddress, $portNumber);
}
```

That means remove [these lines](http://github.com/koraktor/steam-condenser/blob/master/php/lib/steam/sockets/RCONSocket.php#L28-29).

PS: Firewalls could be a problem too, but right now I have to rule out that Steam Condenser is the cause of your problem.

**Comment by Dekkenn** [comment] 2010-10-05 13:28
Done that, the error changed abit now.

PHP Fatal error:  Uncaught exception 'Exception' with message 'Could not connect socket: Success' in /home/dekken2/bot/SteamCondenser/lib/UDPSocket.php:45
Stack trace:
#0 /home/dekken2/bot/SteamCondenser/lib/DatagramChannel.php(47): UDPSocket->connect(Object(InetAddress), 40904)
#1 /home/dekken2/bot/SteamCondenser/lib/steam/sockets/SteamSocket.php(39): DatagramChannel->connect(Object(InetAddress), 40904)
#2 /home/dekken2/bot/SteamCondenser/lib/steam/servers/SourceServer.php(57): SteamSocket->__construct(Object(InetAddress), 40904)
#3 /home/dekken2/bot/servers.php(32): SourceServer->__construct(Object(InetAddress), 40904)
#4 /home/dekken2/bot/functions.php(725): server->is_empty()
#5 /home/dekken2/bot/MainBot.php(65): start_pickup_s3()
#6 /home/dekken2/bot/SmartIRC.php(2356): PickupBot->waitbot(Object(Net_SmartIRC), Object(Net_SmartIRC_data))
#7 /home/dekken2/bot/SmartIRC.php(2007): Net_SmartIRC_base->_handleactionhandler(Object(Net_SmartIRC_data))
#8 /home/dekken2/bot/SmartIRC.php(1377): Net_SmartIRC_base->_rawreceive()
#9 /ho in /home/dekken2/bot/SteamCondenser/lib/UDPSocket.php on line 45

**Comment by koraktor** [comment] 2010-10-05 13:36
Alright, so that's not the real problem &ndash; although I should change that for optimization reasons. ;)

Your code (`servers.php`) mentions the following servers:

```
$servers[1] = new server;
$servers[1]->init("109.236.80.230", "27080", "rconpasshere");

$servers[2] = new server;
$servers[2]->init("109.236.80.230", "27085", "rconpasshere");

$servers[3] = new server;
$servers[3]->init("109.236.80.230", "27090", "rconpasshere");

$servers[4] = new server;
$servers[4]->init("109.236.80.230", "27095", "rconpasshere");
```

You used strings as port numbers there, which seems a bit odd and may cause problems. Port 40904 is not listed there so I don't know if this is a conversion error or intended.

**Comment by Dekkenn** [comment] 2010-10-05 13:42
I edited the code abit.
My servers.php looks like this:

//Create servers and give info
$servers[1] = new server;
$servers[1]->init("212.150.176.35", 40904, "XXXX");

**Comment by koraktor** [comment] 2010-10-05 13:49
Ok, fine. So this isn't an issue either.

I just checked the server my self using my local machine and could get a list of players using the following code:

```
<?php
require_once 'steam-condenser/lib/steam-condenser.php';

$s = new SourceServer(new InetAddress('212.150.176.35'), 40904);
print_r($s->getPlayers());
?>
```

So you might want to try that on another machine first and/or check your servers firewall restrictions.

**Comment by Dekkenn** [comment] 2010-10-05 14:00
And whenever I ran that code:
PHP Fatal error:  Uncaught exception 'Exception' with message 'Could not connect socket: Success' in /var/www/html/koraktor-steam-condenser-d11d8bc/php/lib/UDPSocket.php:45
Stack trace:
#0 /var/www/html/koraktor-steam-condenser-d11d8bc/php/lib/DatagramChannel.php(47): UDPSocket->connect(Object(InetAddress), 40904)
#1 /var/www/html/koraktor-steam-condenser-d11d8bc/php/lib/steam/sockets/SteamSocket.php(39): DatagramChannel->connect(Object(InetAddress), 40904)
#2 /var/www/html/koraktor-steam-condenser-d11d8bc/php/lib/steam/sockets/RCONSocket.php(28): SteamSocket->__construct(Object(InetAddress), 40904)
#3 /var/www/html/koraktor-steam-condenser-d11d8bc/php/lib/steam/servers/SourceServer.php(56): RCONSocket->__construct(Object(InetAddress), 40904)
#4 /var/www/html/index.php(5): SourceServer->__construct(Object(InetAddress), 40904)
#5 {main}
  thrown in /var/www/html/koraktor-steam-condenser-d11d8bc/php/lib/UDPSocket.php on line 45

So probably some problem on my end. I will try contacting the company and asking them about the firewall.
But what could be the problem with the firewall? it blocks connections? eh?? dunno

**Comment by koraktor** [comment] 2010-10-05 14:06
The socket error ("Success") doesn't really provide that much information. I think the firewall might terminate the connection.

Raising PHP's error level might provide further information: `error_reporting(E_ALL)`

**Comment by Dekkenn** [comment] 2010-10-05 14:12
Same output with the reporting level.
I will just contact the vps host.
Thank you for the help!

**Comment by koraktor** [comment] 2010-10-05 15:05
Ok, I'll close this as invalid as it seems to be not related to Steam Condenser.
But feel free to comment again if you need further help.

**Closed as completed** 2010-10-05 22:05 UTC
Labels: invalid

**Comment by Dekkenn** [comment] 2010-10-12 22:30
Any ideas why does this happen?

PHP Fatal error:  Uncaught exception 'TimeoutException' in /root/bot/SteamCondenser/lib/steam/sockets/SteamSocket.php:61
Stack trace:
#0 /root/bot/SteamCondenser/lib/steam/sockets/RCONSocket.php(45): SteamSocket->receivePacket(1440)
#1 /root/bot/SteamCondenser/lib/steam/servers/SourceServer.php(65): RCONSocket->getReply()
#2 /root/bot/servers.php(54): SourceServer->rconAuth('aj94ze068767720')
#3 /root/bot/functions.php(845): server->changelevel('cp_badlands')
#4 /root/bot/MainBot.php(65): start_pickup_s3()
#5 /root/bot/SmartIRC.php(2356): PickupBot->waitbot(Object(Net_SmartIRC), Object(Net_SmartIRC_data))
#6 /root/bot/SmartIRC.php(2007): Net_SmartIRC_base->_handleactionhandler(Object(Net_SmartIRC_data))
#7 /root/bot/SmartIRC.php(1377): Net_SmartIRC_base->_rawreceive()
#8 /root/bot/SmartIRC.php(1359): Net_SmartIRC_base->listenOnce()
#9 /root/bot/bot.php(185): Net_SmartIRC_base->listen()
#10 {main}
  thrown in /root/bot/SteamCondenser/lib/steam/sockets/SteamSocket.php on line 61

It happens once in awhile.
The server is operating, so I don't see why it produces that error.

**Comment by koraktor** [comment] 2010-10-13 04:47
This might have various reasons, but may also be related to the initial problem (unless you are on another machine right now).
The easiest solution for this problem might be wrapping the calls to Steam Condenser in a `try {} catch() {}` block. That way your script won't be stopped each time and you might do what you want after that. For example just try again or wait or whatever.

**Comment by Dekkenn** [comment] 2010-10-13 11:31
Yea I have assumed that is what I should do.
I am on a new machine btw, everything else is sorted out.
I talked with few of my mates, they told me its not the script's problem, it just how steam works, well. its broken :P
They had the same problem with PHP/C# and also HLSW crashes sometimes with the same error.
So I guess all I can do is really try and catch it, and retry the command until it works fine.
Thanks!
