### ISSUE TITLE
java rcon response isn't support utf8

### ISSUE THREAD

**Issue by raydan** [koraktor/steam-condenser#227] opened 2013-10-04 08:36 UTC
java rcon response isn't support utf8 (like status command), when server name contain non ASCII, the result unexpected

**Comment by koraktor** [comment] 2013-10-04 09:46
Thanks for your report.

Can you provide more detail for an "unexpected result"?

Do you have similar problems when getting server info without RCON?

**Comment by raydan** [comment] 2013-10-04 10:58
try to set game server hostname to "점프" or any other non ASCII.

then rcon exec and write to a file or console

after trying can modiy your source, i successful get utf8 response
by modidy RCONExecResponsePacket, PacketBuffer, RCONPacket, SteamPacket

**Comment by koraktor** [comment] 2013-10-04 11:23
I'm not sure if I understood correctly, but if you were able to fix the problem by patching the current code, please provide the code or patch so we can fix this problem.

Otherwise I'm going to reproduce this problem myself.

**Comment by raydan** [comment] 2013-10-04 13:09
don't know how to create a patch, i upload to somewhere
http://www.sendspace.com/file/ck6bdp

**Comment by koraktor** [comment] 2013-10-05 13:11
I haven't been able to reproduce this problem with Java, yet. I'll have a look at your code.

**Comment by koraktor** [comment] 2013-12-06 20:37
@raydan Sorry for the very late reply. I haven't been able to look at the code in the past weeks, can you upload it again?

**Comment by raydan** [comment] 2013-12-09 01:59
here is the files
http://www.sendspace.com/file/sg83er

**Comment by koraktor** [comment] 2013-12-09 05:32
Ok thanks.
I'm still unable to reproduce this on my own test servers. Does this affect a specific game?

 Do you have a server that can be used for testing this (i.e. can you send me a temporary RCON password)?

**Comment by raydan** [comment] 2013-12-09 06:51
hostname or player name contain non ASCII, (chinese, korean, japanese words or other)
when using "status" rcon command, the result string isn't a utf8.
so you write the result string to a text file or insert to database, it become unreadable.

i don't have test server. but you can try to set hostname or playername
example words
안녕하세요
你好
こんにちは

**Comment by koraktor** [comment] 2013-12-09 06:58
I already tried that on my local test server an could not reproduce it.

Do you have more detail on the affected server(s)? Game, version, operating system?

**Comment by raydan** [comment] 2013-12-09 09:29
latest windows 2008 cs:s server

client: windows 7, jdk 7

**Comment by raydan** [comment] 2013-12-09 10:06
server.cfg
hostname "你好 안녕하세요 こんにちは"
save as utf8, no BOM

```


import java.net.InetAddress;
import java.io.*;
import java.util.*;


import com.github.koraktor.steamcondenser.exceptions.RCONNoAuthException;
import com.github.koraktor.steamcondenser.steam.packets.rcon.RCONAuthRequestPacket;
import com.github.koraktor.steamcondenser.steam.packets.rcon.RCONAuthResponse;
import com.github.koraktor.steamcondenser.steam.packets.rcon.RCONExecRequestPacket;
import com.github.koraktor.steamcondenser.steam.packets.rcon.RCONExecResponsePacket;
import com.github.koraktor.steamcondenser.steam.packets.rcon.RCONPacket;
import com.github.koraktor.steamcondenser.steam.packets.rcon.RCONTerminator;
import com.github.koraktor.steamcondenser.steam.sockets.RCONSocket;
import com.github.koraktor.steamcondenser.steam.sockets.SourceSocket;
import com.github.koraktor.steamcondenser.steam.servers.SourceServer;
import com.github.koraktor.steamcondenser.steam.*;

import java.net.*;

public class SrvTest {

    SrvTest()
    {
        try {
            SourceServer server = new SourceServer("127.0.0.1", 27015);
            server.rconAuth("password");
            System.out.println("Connected");
            String str = server.rconExec("status");

            LogData(str);
        } catch(Exception e) {
            e.printStackTrace();
        }

    }

    public static void LogData(String data)
    {
        OutputStreamWriter out = null;
        try{
            out = new OutputStreamWriter(new FileOutputStream("data.txt"),"UTF-8");
            out.write(data);
            out.flush();
            out.close();
        } catch (Exception e) {

        } finally {
            try {
                if(out != null) { out.close(); }
            } catch(Exception e) { }
        }
    }

    public static void main(String[] args) throws Exception
    {
        new SrvTest();
    }

}

```

**Comment by koraktor** [comment] 2014-01-01 10:56
Finally managed to test this. Here's the output from my TF2 test server.

```
hostname: 你好 안녕하세요 こんにちは
version : 2058653/24 2058653 insecure
udp/ip  : 192.168.0.5:27015
account : not logged in  (No account specified)
map     : ctf_2fort at: 0 x, 0 y, 0 z
players : 0 (24 max)

# userid name                uniqueid            connected ping loss state  adr
```

Seems fine to me.

**Comment by raydan** [comment] 2014-01-03 05:22
my result in window cs:s server

123 "頦詹??            STEAM_0: 13:07       34    0 active x:27005
119 "薳?雓遲?????????STEAM_0:1 20:18    39    0 active x:27005

**Comment by koraktor** [comment] 2014-01-03 06:35
Strange, so this seems like a Windows issue to me.
Can you show the exact output of the code snippet above?

Another wild guess: Try setting the `file.encoding` property to `UTF-8`. See [this StackOverflow question](http://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding) for more information.

**Comment by raydan** [comment] 2014-01-03 07:03
you have private email? i sent my game server info to you to let you test

and tested the following
add System.setProperty("file.encoding", "UTF-8");

game server: cs:s window 2008
java client:
window 7 jdk7
debian jdk 7

javac -cp "lib/_" -encoding utf8 *.java  -Xlint:unchecked
java -classpath "lib/_:." SrvTest

all donesn't work

**Comment by koraktor** [comment] 2014-01-04 14:38
My email is koraktor(at)gmail.com. (It can also be found in the README.)

**Comment by koraktor** [comment] 2014-01-07 06:25
This could be resolved with supplying `-Dfile.encoding=UTF-8`. I close this now as your other, probably also encoding related, issues reside in #239 now.

**Closed as completed** 2014-01-07 06:25 UTC
Labels: RCON, Java, invalid, Compatibility
