### ISSUE TITLE
steam community, fetch method + suggestions

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#29] opened 2010-01-30 12:23 UTC
Hey,

i have a array of steam_ids and if i call fetch it raise a exception:
NoMethodError: undefined method `text' for nil:NilClass
/Library/Ruby/Gems/1.8/gems/steam-condenser-0.9.0/lib/steam/community/steam_id.rb:82:in`fetch'

Is it possible to have a invalid SteamId?

Another question, is it possible to get a list of steam friends with one request? (e.G with nickname / realname / status message), or how can i handle a list of e.g. 50 friends? I only get the steam_ids and have to call fetch for each id? This lasts forever :)

Thanks for help & keep up your great work!

**Comment by koraktor** [comment] 2010-01-31 12:05
Thanks for your report. I just tried to solve this...
First of all, the problem is related to parsing the URL of the SteamIDs avatar. So my first idea was, that Valve changed the XML data once again. Usually they send a dummy avatar URL (an image with a question mark) for people who haven't set an avatar. But this didn't change.
So my next idea is, that you either found a SteamID with invalid XML data (really strange) or some other error happened. Can you provide some more information, e.g. the SteamIDs you where querying or the code you where using?

I haven't any good news on your second question either. The real problem here is the download of the data. And right now I can't really see a way to improve this. Maybe there's a way to speed this up, but this won't be a simple code change. I'm going to open another issue for this one as I'm also interested in a solution for this performance bottleneck.

**Comment by idev** [comment] 2010-01-31 12:15
I notice this behaviour at these SteamIds 76561197960550373
and 76561197984844491. Hope this helps!

**Comment by koraktor** [comment] 2010-01-31 12:25
Thanks for your fast response.
Both SteamIDs display the following message: _"This user has not yet set up their Steam Community profile"_. This is rather odd, ass the message isn't enclosed in a `<error>` tag as when you search for an invalid SteamId, but in a (what seems to be new) `<privacyMessage>` tag.
As there's no actual documentation of the XML data of SteamIDs I hope there are no other changes like this.

**Comment by idev** [comment] 2010-01-31 12:42
sounds like great documented Steam XML :)

**Comment by koraktor** [comment] 2010-01-31 16:55
Fixed errors on somehow deactivated or blocked SteamIDs

These SteamIDs have no real content in their XML data, but a text in the <privacyMessage> tag.

Closed by cc1afb4267787b74dc371925fd6bc2b00055a62a

**Closed as completed by koraktor** 2010-01-31 16:55 UTC
Labels: Bug
