### ISSUE TITLE
[Ruby] redirection forbidden on numeric steamIDs

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#38] opened 2010-02-17 13:41 UTC
Hey,
sometimes i get the following error:

```
redirection forbidden: http://steamcommunity.com -> https://steamcommunity.com/

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb in open_loop
      raise "redirection forbidden: #{uri} -> #{redirect}"
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb in open_uri
io = open_loop(uri, options)
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb in open
  OpenURI.open_uri(self, *rest, &block)
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb in open
  uri.open(*rest, &block)
/Library/Ruby/Gems/1.8/gems/steam-condenser-0.9.0/lib/steam/community/extension.rb in fetch_extended
profile_url = open(base_url + '?xml=1', {:proxy => true})
```

a (sinatra) restart fixes the issue. Can anybody confirm this?
It only happens with numeric SteamIds, CustomURLs always works.

**Comment by koraktor** [comment] 2010-02-17 13:56
Redirection seems to be broken on Steam Community's end. While opening a profile with the numeric ID redirected to the custom URL (if existing) before, it now redirects to the start page. Additionally the start page always redirects to HTTPS, therefore the error message you get.

What I don't understand is how restarting sinatra fixes this for you. It seems like Steam Community always does the redirect.

**Comment by idev** [comment] 2010-02-17 14:46
Hm, so it seems redirect works once and is then broken?
Perhaps sinatra dont close the connection correctly?

Weird.

**Comment by idev** [comment] 2010-02-17 15:49
Perhaps my ruby version is simple not up to date
http://redmine.ruby-lang.org/issues/show/859

I use: ruby 1.8.7 (2008-08-11 patchlevel 72) [universal-darwin10.0]

**Comment by koraktor** [comment] 2010-02-17 15:55
Forgot what I said. I tried the wrong URL: `steamcommunity.com/profile/...` instead of `steamcommunity.com/profiles/...`

Seems like your right. It's a bug in open-uri. But nevertheless the Steam Community is behaving odd, too. Sometimes it redirects to HTTPS, sometimes it doesn't.

But most likely, this can't be fixed on my side, so this is a **won't fix**.

**Comment by idev** [comment] 2010-02-17 16:19
Tried ruby 1.8.7 (2009-12-24 patchlevel 248) [i686-darwin10.2.0] but same error.

**Comment by idev** [comment] 2010-02-17 16:32
So i updated my open-uri.rb:
http://redmine.ruby-lang.org/issues/show/859
And it seems to work, i dont get the redirect error.. but now it seems that i get no response:
  <code>NoMethodError at
  undefined method `text' for nil:NilClass</code><br/>
Line in code:
  <code>@image_url        = profile.elements['avatarIcon'].text[0..-5]</code>

Is the redirect necessary? Or could it be fetched always against https?

**Comment by idev** [comment] 2010-02-17 16:50
So, some more tracing, when the redirect fails it displays the http://steamcommunity.com login page.

Great behavior steam!!!!

**Comment by koraktor** [comment] 2010-02-18 07:17
Could you provide any additional information? What profile are you querying?

PS: Seems like Steam Community doesn't redirect anymore when using `?xml=1`. Just as intended. So it works for me now.

**Comment by jouva** [comment] 2010-02-18 15:04
I recall getting this when doing a /profile/ when I meant /id/, or vice versa, but I'm pretty sure you already have this covered with the getBaseUrl call. But yes a 404 leads you to the login page.

**Comment by idev** [comment] 2010-02-18 18:02
I get this error right now for the id 76561197993941053. The Error is not depdendent to a specific id, but i notice it only happens with numeric ids.. custom_url works always for me.

And, if i once get the error, ill get it on every id till i restart my sinatra server. Only custom_urls keep working. This driving me nuts.

@koraktor: but open appends <code>?xml=1</code> already?

**Comment by koraktor** [comment] 2010-02-18 18:18
I don't get the error for this ID. Additionally this ID doesn't have a custom URL, so there isn't even a URL it could redirect to.

`?xml=1` is only for typing the URL in your browser. I use this to quickly check if Steam Community redirects correctly.

**Comment by idev** [comment] 2010-02-18 18:50
Ok, i think i come closer to the error. If i match a id twice, it seems to me the base_url is not set correctly.

i call once
<code>
76561197986867262
base_url:
http://steamcommunity.com/profiles/76561197986867262
fetch .....
fetch done ....
</code>
but the second request looks like:
<code>
76561197986867262
base_url:
http://steamcommunity.com/id/
fetch .....
NoMethodError - undefined method `text' for nil:NilClass:
</code>

**Comment by idev** [comment] 2010-02-18 19:20
hm.. seems to me something is odd with custom_url / base_url.
On the second request, custom_url is not nil, so i get a base_url with /id/.... and this fails.

But im not able to see how to fix this.

Perhaps i use "fetch" in a wrong way?
<code> 
result = SteamId.new(steam_id, false)
result.fetch</code>

Ok, last edit:
Is it possible that custom_url is cached with an empty string, and not nil?

**Comment by koraktor** [comment] 2010-02-19 06:35
Yeah, that's it. But there's nothing cached.
The problem is, that I check against `nil` for Ruby, `null` for Java and `empty()` for PHP while getting the base URL. It seems like the XML format changed a bit and now has empty tags for unset fields, like the custom URL.
So the first fetch will have no value for the custom URL, but the following fetches will have an empty string.

**Comment by jouva** [comment] 2010-02-19 06:38
And empty() in PHP means NULL, FALSE, 0, "0", "", array() and an unset variable in a class. So PHP has probably not seen this error.

**Comment by idev** [comment] 2010-02-19 12:23
Great to hear thats reproducible :)

**Comment by koraktor** [comment] 2010-02-20 14:12
Java / Ruby: Fixed empty custom URLs after fetching SteamIDs without custom URL

Closed by 8ff7c989d0d3e950d2b251186191eceb5e9e374b

**Closed as completed by koraktor** 2010-02-20 14:12 UTC
Labels: Ruby, Java

**Comment by idev** [comment] 2010-02-21 17:27
Hey,

i changed the line as shown in your commit at steam_id.rb but i notice the same behavior. At the second request a got a empty string. (Frist one is nil).

Am i missing something?

**Comment by koraktor** [comment] 2010-02-21 17:55
I can't reproduce this. This works for the ID you mentioned above (76561197986867262).

**Comment by idev** [comment] 2010-02-21 18:04
just ignore my last posts.. my fault! i overwrite your fetch method.. ;) so i have to fix it at my place.. SORRY!!!! :)
