### ISSUE TITLE
Ruby - Player Score is wrong if Player has -1

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#13] opened 2009-06-05 17:46 UTC
Hey,

if a player has -1 score it would returned as huge number like 4294967295, seems to be a conversion failure?

greetings

**Comment by idev** [comment] 2009-06-05 17:52
Some additional Infos, the negative values are returned as Bignum, the positive as Fixnum.
Hope this helps a little.

**Comment by koraktor** [comment] 2009-06-07 11:43
This is caused by a change done in 17f210c0fab50464ff6526807b2c91efc53efcf9. I changed long integer values to be read as unsigned, but forgot that player scores are also saved as long values - and they can be negative.
I'll have a fix for this soon.

**Comment by koraktor** [comment] 2009-06-07 12:05
Ruby: Fixed issues introduced in 17f210c0fab50464ff6526807b2c91efc53efcf9.

Closed by 87124be6aaf7aa305e032b7b692121f3f417d78a

**Closed as completed by koraktor** 2009-06-07 12:05 UTC
Labels: Ruby, Bug
