### ISSUE TITLE
Fatal error in SourceServer

### ISSUE THREAD

**Issue by deStrO** [koraktor/steam-condenser#189] opened 2013-01-11 21:52 UTC
Hello,

I'm using Steam-Condenser PHP for my project (eBot-CSGO), and there is a fatal error that I can't handle.

PHP Fatal error:  Call to a member function getRequestId() on a non-object in /data/website/esport-tools/ebotv3/vendor/koraktor/steam-condenser/lib/steam/servers/SourceServer.php on line 109

I'm using the version 1.3.0 (with composer).

Any fix for this ?

Thanks !
Julien

**Comment by koraktor** [comment] 2013-01-12 14:17
That line is part of `SourceServer::rconAuth()`. What are you trying to do?

**Comment by deStrO** [comment] 2013-01-12 14:22
I'm doing this:

``` php
$this->server = new \SourceServer($this->getIp(), $this->getPort());
try {
    $this->server->rconAuth($this->getRcon());
    $this->status = true;
    return true;
} catch (\Exception $e) {
    $this->error = $e->getMessage();
    $this->status = false;
    return false;
}
```

I don't have the "data".

You can find the source here: https://github.com/deStrO/eBot-CSGO/blob/master/src/eTools/Rcon/CSGO.php

**Comment by koraktor** [comment] 2013-01-12 14:27
The `rconAuth()` code was never very pretty. Maybe CS:GO handles this a bit differently. I'll try to set up a test server for this.

**Comment by deStrO** [comment] 2013-01-12 14:32
I had this error once on lot of use

I had ~750 matches that use this class and I got this error last night.

**Comment by koraktor** [comment] 2013-01-12 18:09
Probably found the root cause for this. This might have been fixed in koraktor/steam-condenser-php@8122564a49534407dbb70f45315a5cc338a4ed8d. Maybe you want to check this.

**Comment by koraktor** [comment] 2013-01-13 00:01
To clarify this a bit, the old version (i.e. 1.3.0) did return a `null` reply for all socket exceptions, thus causing `rconAuth()` to fail ugly. The fix will only return `null` when the connection was reset, e.g. during a map change. This will cause a (usually) successful retry and don't fail. All other exceptions, e.g. when the server is down, will cause `SocketException`s.

**Comment by deStrO** [comment] 2013-01-14 11:29
Ok, thanks ! =)

I updated to the last version to try. I will let you know if I see this error again

Thanks !

**Comment by deStrO** [comment] 2013-01-14 21:40
I got again the same error. Did you update the package ?

Fatal error: Call to a member function getRequestId() on a non-object in /data/website/esport-tools/ebotv3/vendor/koraktor/steam-condenser/lib/steam/servers/SourceServer.php on line 109

**Comment by koraktor** [comment] 2013-01-14 22:04
> Did you update the package ?

The question is, did you update your copy? :grinning:

You should probably, because I just pushed a new patch that further improves RCON connection handling.

**Comment by koraktor** [comment] 2013-01-19 21:29
@deStrO Any new on this issue? I'd love to release version 1.3.1 in the coming days, but I want to resolve this first.

**Comment by deStrO** [comment] 2013-01-20 11:18
It seems good now, didn't get the error since I updated.

But now I have a lot of "Not authenticated yet." that I have to fix ! :D

**Comment by koraktor** [comment] 2013-01-20 11:58
Great, I'll close this now.

Version 1.3.1 will be released today or tomorrow.

**Closed as completed by koraktor** 2013-01-20 11:58 UTC
Labels: RCON, PHP, Bug

**Comment by deStrO** [comment] 2013-02-02 16:03
Hello,

I got the error again.

PHP Fatal error:  Call to a member function getRequestId() on a non-object in /var/www/eBot-CSGO/vendor/koraktor/steam-condenser/lib/steam/servers/SourceServer.php on line 109
Fatal error: Call to a member function getRequestId() on a non-object in /var/www/eBot-CSGO/vendor/koraktor/steam-condenser/lib/steam/servers/SourceServer.php on line 109

It happened on a change level (I'm using the last version of steamCondenser)

**Comment by koraktor** [comment] 2013-02-02 22:45
Since version 1.3.1 `RCONSocket::getReply()` can no longer return `null` (or some other non-object). Are you sure you are one the latest version?

**Comment by deStrO** [comment] 2013-02-16 22:01
I didn't saw your answer.

Yes, I'm using that version. I use composer to get up to date.

**Comment by koraktor** [comment] 2013-02-16 22:08
So you should be at 1.3.3 now. Can you still reproduce this? And if so, can you tell me some way to do so?
