### ISSUE TITLE
When issuing a map command with rcon_exec I get a broken pipe

### ISSUE THREAD

**Issue by pcasaretto** [koraktor/steam-condenser#145] opened 2012-01-28 18:57 UTC
``` bash
1.9.2-p290 :031 > server.rcon_auth('...')
 => true 
1.9.2-p290 :032 > server.rcon_exec('status')
 => "hostname: Test Server 1[BR]\nversion : 2.0.9.7 4777 secure  (unknown)\nudp/ip  : 10.252.0.10:27015 [ public 177.71.138.143:27015 ]\nos      : Linux Dedicated\nmap     : c1m1_hotel\nplayers : 0 humans, 0 bots (4 max) (hibernating) (unreserved)\n\n# userid name uniqueid connected ping loss state rate adr\n#end" 
1.9.2-p290 :033 > server.rcon_exec('map c1m1_hotel versus')
SteamCondenser::TimeoutError: The operation timed out.
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.1.0/lib/steam/sockets/steam_socket.rb:56:in 'receive_packet'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.1.0/lib/steam/sockets/rcon_socket.rb:80:in 'reply'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.1.0/lib/steam/servers/source_server.rb:89:in 'rcon_exec'
    from (irb):33
    from /Users/pcasaretto/.rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in '<main>'
1.9.2-p290 :034 > server.update_ping
 => 43.477000000000004 
1.9.2-p290 :035 > server.rcon_exec('status')
RCONBanError: You have been banned from this server.
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.1.0/lib/steam/sockets/rcon_socket.rb:80:in 'reply'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.1.0/lib/steam/servers/source_server.rb:89:in 'rcon_exec'
    from (irb):35
    from /Users/pcasaretto/.rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in '<main>'
1.9.2-p290 :036 > server.rcon_exec('status')
Errno::EPIPE: Broken pipe - send(2)
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.1.0/lib/steam/sockets/steam_socket.rb:83:in 'send'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.1.0/lib/steam/sockets/steam_socket.rb:83:in 'send'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.1.0/lib/steam/sockets/rcon_socket.rb:67:in 'send'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.1.0/lib/steam/servers/source_server.rb:84:in 'rcon_exec'
    from (irb):36
    from /Users/pcasaretto/.rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in '<main>'
1.9.2-p290 :037 > server.rcon_auth('...')
Errno::EPIPE: Broken pipe - send(2)
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.1.0/lib/steam/sockets/steam_socket.rb:83:in 'send'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.1.0/lib/steam/sockets/steam_socket.rb:83:in 'send'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.1.0/lib/steam/sockets/rcon_socket.rb:67:in 'send'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.1.0/lib/steam/servers/source_server.rb:67:in 'rcon_auth'
    from (irb):37
    from /Users/pcasaretto/.rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in '<main>'
1.9.2-p290 :038 > 
```

Is this expected?

**Comment by koraktor** [comment] 2012-01-28 20:33
This is probably a duplicate of issue #144. I have not started to elaborate on that one yet, but I might switch from the "response means success" method to "delivery means success". As Source uses TCP we'd just need to check if the command arrived, not if we get a reply from the server.

I'll close this issue and reopen #144 for further discussion.

**Closed as completed** 2012-01-28 20:34 UTC
Labels: RCON, Source servers
