### ISSUE TITLE
Doesn't work with ruby 1.9.2

### ISSUE THREAD

**Issue by txdv** [koraktor/steam-condenser#82] opened 2010-10-26 01:45 UTC
I tested it with ruby 1.9.2 and sadly it doesn't work.

**Comment by koraktor** [comment] 2010-10-26 04:36
What does not work? Sorry, can't reproduce any problems right now.

**Comment by txdv** [comment] 2010-10-26 04:44
There is an implementation related error, which will be fixed only in 1.9.3 but furthermore the socket API seems to have changed.

**Comment by koraktor** [comment] 2010-10-26 04:54
Ok, seems like the sockets have to be adapted.

Do you have any more information about the implementation error that will be fixed in 1.9.3?

**Comment by txdv** [comment] 2010-10-26 05:23
"super from singleton method that is defined to multiple classes is not supported.  This will be fixed in 1.9.3 or later"

It affects the AbstractClass

**Comment by koraktor** [comment] 2010-10-26 05:49
Almost knew that. `AbstractClass` doesn't exist anymore. First because of this incompatibility and second because it was unrubyish.

**Comment by txdv** [comment] 2010-10-26 06:21
O, so maybe a git pull would help :)
Wait for wait for it... hmm.

`packet_from_data': Unknown packet with header 0x0 received. (SteamCondenserException)

That's the second error I get.
Tried out with 1.9.1 and 1.9.2 using rvm: http://rvm.beginrescueend.com/

**Comment by txdv** [comment] 2010-10-27 08:21
Please take a look on that, I want to get an irc bot running with steam condenser :D

**Comment by koraktor** [comment] 2010-10-27 08:29
Sure... once I find some time. ;)

**Comment by txdv** [comment] 2010-10-27 08:30
"iiicchhh wiiiillll jeeetzzzttt sppieeeeeleeeeen" 

Have you tried out rvm out?

**Comment by koraktor** [comment] 2010-10-27 08:33
Of course, but fixing the sockets for 1.9.2 doesn't seem to be that trivial and I didn't have any time to have a look at it, yet.

**Comment by koraktor** [comment] 2010-10-29 05:22
Just to keep you updated: I'm restoring my old virtual testing environment from a backup right now. Had been accidentally deleted while cleaning my drive.
Once I have this running again, I can easily start debugging the Ruby code on 1.9. Hope I'll have a fix out by the weekend.

**Comment by koraktor** [comment] 2010-10-30 09:15
Ruby: Fixed several incompatibilities to Ruby 1.9

Closed by 886011921550bcaaec093287b09eae0a097c60bc

**Comment by txdv** [comment] 2010-10-30 10:52
I just jizzed in my pants.

**Closed as completed** 2010-10-30 16:15 UTC
Labels: Ruby, Compatibility
