### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by sleepykhanhle** [koraktor/steam-condenser#159] opened 2012-04-26 05:32 UTC
Help me when I try to run steam-consender.php it gives me this error:

Strict Standards: Redefining already defined constructor for class Socket in C:\AppServ\www\SC\lib\Socket.php on line 169

Fatal error: Declaration of RCONSocket::send() must be compatible with that of SteamSocket::send() in C:\AppServ\www\SC\lib\steam\sockets\RCONSocket.php on line 108

**Comment by koraktor** [comment] 2012-04-26 07:29
You're probably using PHP 5.4, since 5.4 error reporting includes strict errors. You can disable it:

``` php
<?php
error_reporting(E_ALL ^ E_STRICT);
```

Nevertheless, this should be fixed.

**Comment by sleepykhanhle** [comment] 2012-04-26 11:05
Where do I put this?
BTW:I think my Apache uses php6(cause in the Apache folder there's a folder called php6)

**Comment by koraktor** [comment] 2012-04-26 11:10
You should put this in some "global" file, either some configuration file (or maybe even an `index.php`) of your application or you can also change this inside the `php.ini` of your Apache.

PS: PHP 6 hasn't been released yet.

**Comment by sleepykhanhle** [comment] 2012-04-26 11:24
Oh,well I don't see any php.ini,I only see some php.ini-recommended etc...or should I download the newest version of php?

**Comment by koraktor** [comment] 2012-04-26 11:26
Well, let's make this a bit easier.

Just put the `error_reporting` line right above the line where you require or include `steam-condenser.php`. That should be enough.

**Comment by sleepykhanhle** [comment] 2012-04-26 11:30
Erm but....there's many files require/include it so I put it in them all?and about error_reporting you mean 
<?php
error_reporting(E_ALL ^ E_STRICT);
?
I will try to do it and try to update php and will report if it works or not to you later

**Comment by sleepykhanhle** [comment] 2012-04-26 14:15
Doesn't work! After I put it only the strict error disappear

Deprecated: Call-time pass-by-reference has been deprecated in C:\AppServ\www\SSMS\servers.php on line 294

Deprecated: Call-time pass-by-reference has been deprecated in C:\AppServ\www\SSMS\servers.php on line 294

Deprecated: Call-time pass-by-reference has been deprecated in C:\AppServ\www\SSMS\servers.php on line 336

Deprecated: Call-time pass-by-reference has been deprecated in C:\AppServ\www\SSMS\servers.php on line 336

Fatal error: Declaration of RCONSocket::send() must be compatible with that of SteamSocket::send() in C:\AppServ\www\SSMS\lib\steam-condenser\steam\sockets\RCONSocket.php on line 108

**Comment by sleepykhanhle** [comment] 2012-04-26 14:22
And if I put <?php before the error_reporting I got this only

Parse error: syntax error, unexpected '<' in C:\AppServ\www\SSMS\servers.php on line 5

**Comment by koraktor** [comment] 2012-04-26 20:08
Try again with `error_reporting(E_ALL & ~(E_NOTICE | E_DEPRECATED | E_STRICT))`. This should disable those errors.

I'm going to fix the cause of this problem soon.

**Comment by sleepykhanhle** [comment] 2012-04-27 01:25
Now got this problem
Parse error: syntax error, unexpected T_REQUIRE_ONCE in C:\AppServ\www\SSMS\servers.php on line 6
P.S Error_reporting is line 5
Line 6:
require_once 'lib/steam-condenser/steam-condenser.php';

**Comment by koraktor** [comment] 2012-04-27 04:50
Check your syntax, you probably forgot a semicolon.

**Comment by koraktor** [comment] 2012-04-27 07:39
I just fixed these problems in the `master` branch. You can download the current code from https://github.com/koraktor/steam-condenser-php/zipball/master.

**Comment by sleepykhanhle** [comment] 2012-04-27 10:23
Ermm I used it and this seems to be the last problem I have
Fatal error: Call to undefined function getopt() in C:\AppServ\www\SSMS\servers.php on line 17
It seems like the new update of steam condenser fixed problems but also made new problems,this is line 17
if(isset($_SERVER['argc'])) $args = getopt("u");
if you want the whole servers.php here
http://www.mediafire.com/?m5k3649z4mgpsc4
And I contacted the creator of the plugin to download your new patch,but I just want you to see the plugin so you can see if you can fix it

**Comment by koraktor** [comment] 2012-04-27 10:36
`getopt()` should be part of PHP and Steam Condenser doesn't interfere with that (and SSMS probably, too)

**Comment by sleepykhanhle** [comment] 2012-04-27 10:49
What do you mean?Can you fix it?

**Comment by koraktor** [comment] 2012-04-27 11:57
No sorry. I don't know what's wrong here. And I won't dig into third-party code.

**Comment by sleepykhanhle** [comment] 2012-04-27 13:01
Ok will will contact the creator then,thanks for fixing the steam condenser anyway!

**Closed as completed** 2012-04-28 22:48 UTC
Labels: PHP, Compatibility
