### ISSUE TITLE
When fetching profiles, some profiles yield "XML parse error"

### ISSUE THREAD

**Issue by avesst** [koraktor/steam-condenser#177] opened 2012-12-17 19:55 UTC
I have no idea if I'm supposed to add this here. But I figured since I cannot get any answer elsewhere. And several people I've talked with are having the same problem.

The problem is described in this StackOverflow post http://stackoverflow.com/questions/13915853/rubygem-steam-condenser-why-can-i-only-fetch-some-profiles

**Comment by koraktor** [comment] 2012-12-17 21:27
It's totally fine to report problems here.

This problems was caused by Valve changing the XML output slightly a few months back. It was already fixed in [this commit](https://github.com/koraktor/steam-condenser-ruby/commit/98be68d6f4d506531a4226db876d1b18efae78fe).

Sadly, I haven't found the time to release a new version yet. Sorry about that, but you should have no problem using the `master` version of the code – especially if you use Bundler for your dependencies.

**Closed as completed by koraktor** 2012-12-17 21:27 UTC
Labels: Ruby, invalid, Community

**Comment by avesst** [comment] 2012-12-17 23:32
Thanks alot! Do you mean I can use the code in "master", but it will fail if I try to use the gem?
