### ISSUE TITLE
Problem With Steamid.methods, ruby

### ISSUE THREAD

**Issue by icehaku** [koraktor/steam-condenser#178] opened 2012-12-21 18:52 UTC
Hi, I'm trying to use the methods of Steamid and I'm having some problems:

Samples:
When I try this:
    @steam_profile = SteamId.new 'ice_haku'
    stats = @steam_profile.game_stats 'hl2' 
or
    stats = @steam_profile.game_stats 'tf2'
I get this:
    undefined method `[]' for nil:NilClass

Or another methods:
    :favorite_game, 
# nil

```
:favorite_game_hours_played,
```
# nil

```
:friends
```
# []

Most of methods works fine. Am I doing something wrong?

**Comment by koraktor** [comment] 2012-12-21 22:15
The profile `ice_haku` doesn't have stats for TF2 or HL2, so the output isn't that wrong, although the current code of Steam Condenser provides better error handling. You may want to try this, too.

The favorite game is no longer provided by Steam Community and those methods will be removed from future versions.

I wasn't able to reproduce the problem with `#friends` yet, because I currently get a lot of HTTP 503 errors from Steam Community, but

**Comment by koraktor** [comment] 2012-12-27 12:25
Friends are working fine with code from `master` now, so I'm going to close this issue.

**Closed as completed by koraktor** 2012-12-27 12:25 UTC
Labels: Ruby
